---
- name: check for existence of devices
  hosts: prod
  tasks:
  - name: Проверка наличия /dev/sda
    debug:
      msg: Есть устройство ==> /dev/sda
    when: ansible_facts['devices']['sda'] is defined

  - name: Проверка наличия /dev/sdb exists
    debug:
      msg: Есть устройство ==>  /dev/sdb
    when: ansible_facts['devices']['sdb'] is defined

  - name: Проверка отсутствия /dev/sdc
    debug:
      msg: Нет такого устройства ==> /dev/sdc
    when: ansible_facts['devices']['sdc'] is not defined
