prod:
  hosts:
    serv3:
      ansible_host: serv3
      ansible_ssh_user: semaphore
      ansible_ssh_pass: 1234
dev:
  hosts:
    serv1:
      ansible_host: serv1
      ansible_ssh_user: semaphore
      ansible_ssh_pass: 1234
    serv2:
      ansible_host: serv2
      ansible_ssh_user: semaphore
      ansible_ssh_pass: 1234
myhosts:
  children:
    dev:
    prod:
