---
- name: Выводим на экран информацию о серврах
  hosts: all
  become: true

  tasks:
    - name: System information
      debug:
        msg:
          - "Owner: {{ owner }}"
          - "Distribution: {{ ansible_distribution }} --> version: {{ ansible_lsb.description }}"
          - "FQDN: {{ ansible_fqdn }}"
          - "Package manager: {{ ansible_pkg_mgr }}"
          - "CPU: {{ ansible_processor_cores }}"
          - "Uptime hours: {{ (ansible_uptime_seconds / 60 / 60) | round(2) }}"

    - name: Свободное место на диске
      debug:
        msg: "{{ ansible_mounts[0].device }}: {{ (ansible_mounts[0].size_total / 1024 / 1024 / 1024) | round(2) }} GB"
      when: ansible_mounts | length > 0
      delegate_to: linux1

    # Сохраняем информацию о событиях на хосте ansible
    - name: Записываем инормацию о событии на ansible master
      shell: echo This task was executed on server - {{ inventory_hostname }} / {{ owner }} >> /files/reg.txt
      delegate_to: 127.0.0.1 # Ansible master

    - name: Одноразовая операция
      ping:
      run_once: true
