---
- name: Выводим на экран информацию о серверах
  hosts: all
  become: false

  tasks:
    - name: System information
      debug:
        msg:
          - "Distribution: {{ ansible_distribution }} --> version: {{ ansible_lsb.description }}"
          - "FQDN: {{ ansible_fqdn }}"
          - "Package manager: {{ ansible_pkg_mgr }}"
          - "CPU: {{ ansible_processor_cores }}"
          - "Uptime hours: {{ (ansible_uptime_seconds / 60 / 60) | round(2) }}"
          - "Owner: {{ owner }}"
